---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    theme: journal
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(stringr)

library(flexdashboard)
```

Column {data-width=550}
-----------------------------------------------------------------------

# Dashboard of plots about produce and berry items
## Dashboard
### Scatterplot: N of orders vs % that were one of 1st five in cart for produce
```{r}
data("instacart")

instacart_df = 
  instacart %>%
  na.omit(instacart) %>% #omitting any NA
  select(order_id, add_to_cart_order, reordered, user_id, order_dow, order_hour_of_day, product_name, department) %>% #Selecting variables
  filter(str_detect(product_name, "Organic"), # Only organic items are shown
         reordered == "0", order_dow == "1", #Only 1st time orders that were ordered on Sunday(1) are shown. 
         department %in% c("produce")) %>% # Only include produce 
  mutate(product_name = str_replace_all(product_name, 
                                        c("Organic Bluberries" = "Organic Blueberries", 
                                          "Organic Blueberry" = "Organic Blueberries"))) #There were multiple names for blueberries
```

```{r}
#Set up data for scatterplot
produce_1to5 <- instacart_df %>% 
  group_by(product_name) %>%   # Group by product name
  summarize(
    total_count = n(),    # Count total purchases of each product
    order_count = sum(add_to_cart_order %in% 1:5) # % where that was one of the 1st five products they put in their cart
  ) %>%
    filter(total_count > 1) %>% #Removed foods where there was only 0 or 1 bought because it was messing with the graph
  mutate(order_percent = (order_count / total_count) * 100) # Calculate percentage for the amount of orders


produce_1to5 %>%
  mutate(text_label = str_c("Product Name:", product_name)) %>%
  plot_ly(x = ~total_count, y = ~order_percent, color = ~product_name, type = "scatter", mode = "markers", colors = "viridis") #when the legend is on there, it only shows the legend in website, not the graph itself
```

Column {data-width=450}
-----------------------------------------------------------------------

### Barplot: Number of berry products sold

```{r}
instacart_df %>%
  count(product_name) %>%
  filter(str_detect(product_name, "berries|berry|Berries|Berry")) %>%
  mutate(product_name = fct_reorder(product_name, n)) %>%
  plot_ly( 
    x = ~product_name, y = ~n, 
    color = ~product_name, type = "bar", colors = "viridis")
```

### Boxplot: Time of day when berries were sold

```{r}
instacart_df %>%
    filter(str_detect(product_name, "berries|berry|Berries|Berry")) %>%
  plot_ly( 
    x = ~product_name, y = ~order_hour_of_day, 
    color = ~product_name, type = "box", colors = "viridis")
```

